export { default as Home } from 'templates/Home'
export { default as Member } from 'templates/Member'
export { default as Board } from 'templates/Board'
export { default as Item } from 'templates/Item'
export { default as Stock } from 'templates/Stock'